--- #YAML:1.0
name:                Test-MockDBI
version:             0.64
abstract:            Mock DBI interface for testing
license:             ~
author:              
    - Mark Leighton Fisher <mark-fisher@fisherscreek.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    DBI:                           0
    File::Spec::Functions:         0
    Test::MockObject:              0.14
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
