--- #YAML:1.0
name:               Test-MockDBI
version:            0.66
abstract:           Mock DBI interface for testing
author:
    - Mark Leighton Fisher <mark-fisher@fisherscreek.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    CPAN::Meta:  0
requires:
    DBI:                  0
    File::Spec::Functions:  0
    Test::MockObject:     0.14
    Test::More:           0
    Test::Warn:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
